### ISSUE TITLE
Product manager interview: Sofia Gonçalves

### ISSUE THREAD

**Issue by donbonifacio** [donbonifacio/blog#103] opened 2018-08-16 12:34 UTC
Pipeline:

- [x] Priorites are defined by the user, how do you know the priority when you have thousands of users?
- [ ] Interactions with designers
- [ ] How to mentor product managers

**Comment by donbonifacio** [comment] 2018-08-16 12:34
Hello Sofia. Can you introduce yourself and talk a bit about your background and what you do?

**Comment by SofiaPGoncalves** [comment] 2018-08-20 17:59
Hi :-)

Thanks for the question, happy to be part of this. 

I'm Sofia Gonçalves and I'm a Product Manager. Although Portugese, I have lived in different European Countries and I'm now based in London. 

My background is different than what I do now - I used to be a Clinical Psychologist and studied a lot in that area. Around 5/6 years ago, I realised that although I learned a lot about people's behaviours and enjoyed my time as a psychologist, I didn't see myself doing that for the rest of my life. I decided to change careers. The problem was, I didn't know what I wanted to do. I enrolled in an MBA program (in ESADE) so that I could expand my knowledge about business and expand my network. 

At the end of my MBA I was trying to get a job, but I wasn't sure in what. One of my final classes gave me the indication of the industry I wanted to work in - technology. It is thanks to Prof Luis Vives that I understood of my value and interest in this industry. I landed in Product management a bit by accident, and like most, I have learned it by doing it. 

Explaining what a product manager does is always funny, because it is hard to explain it, if you have not worked in tech. I usually say if I had to explain to a 5-year-old what I do, they would be disappointed. I don't code, I don't design or work with social media. And yet, we need to understand a bit of all of those things. We have to be the ones driving people's work in the right direction and defend the product's vision, making sure everyone is working towards the same goal. 

I have worked with SaaS product and websites, and have alwats learned a lot with the teams I was part of. All of them were quite diverse, which made it fun. 

At the moment I work in London for the amazing company resolver.co.uk - we help clients and companies get into a better agreemebnt if there was a disagreement over a serivce or product. I deal with a SaaS product, helping small business grow, by dealing with their own set of clients.  I love being here mostly because it is an amazing team, that respects you and helps you grow, whilst doing something good for people - we help resolve issues they have with companies :-) 

Thanks!

**Comment by donbonifacio** [comment] 2018-08-21 06:48
So how would you explain what a product manager does? What are your day to day tasks and what are you responsible for delivering?

**Comment by SofiaPGoncalves** [comment] 2018-09-02 19:05
Explaining what a product manager does is always funny, because it is hard to explain it, if you have not worked in tech. I usually say if I had to explain to a 5-year-old what I do, they would be disappointed. I don't code, I don't design or work with social media. And yet, we need to understand a bit of all of those things. We have to be the ones driving people's work in the right direction and defend the product's vision, making sure everyone is working towards the same goal. 

Often people say we are like a CEO of the product, but I disagree. Ultimately, I do not have the final word of what happens to the product - the CEO of the company does. As a product manager you often are the one talking with different members of the team, to understand how you can achieve things and solve problems. The product manager is, indeed, an immense advocate of the users and their needs, which means we need to be their voice in the company. This can mean we need to explain to people in the company why certain ideas are not good - we need to understand how those ideas would actually go against the product's vision and the users' needs. Other times, the idea is good and we need to understand how to integrate with the rest of the work being done and how to prioritise certain features. 
I usually say product management is ideal for people who are problem solvers - that is basically what you do. You try to solve as many problems as you can, so that the team can work without any blockers. 

On a day-to-day (and depending on the company) you are organising other people's work. This means sometimes working on strategy, looking at Jira boards to help prioritise tasks and writing requirements of future tasks or talking with users so you are in touch with their needs. Sometimes this means meetings, other times just lone work. 

It is a fun job, but sometimes it can be frustrating. If you cannot help your team to move forward you feel you have failed, so a certain stamina is required to be a product manager. I love it though :-)

**Comment by donbonifacio** [comment] 2018-09-04 10:14
Imagine that there is a feature to be done. From your point of view, what would be the best process going for an idea to a deliverable?

**Comment by SofiaPGoncalves** [comment] 2018-09-12 09:59
I always try to involve the entire team in the process- sometimes that is a challenge if, like me, half your team is office based and the other half remote. It changes the dynamic and you struggle to find the best way to collaborate (although it is not impossible).
I try to understand the idea how actually how to break it down - sometimes it can be one feature, other times in needs to be broken down into more. Once I fully understand or at least have as much information I can get, I will go to development team and discuss it with them. Although I need to understand how technology works, they are the experts and understand, for example, the implications in developing something and how it can affect the rest of the system (and what to do to avoid complications). Once that has been discussed and agreed as a team, I will go to design/front end team and with some rough wireframes we will discuss the feature(s). It is here where you think a lot about the user, UX requirements and how the user journey should be smooth and not complicated. 
Once you have requirements and designs done it is a question of understanding when it can be done - that has to do with **priorities**. You, as a product manager, need to understand what has been agreed to be done before and when you can do this feature. Priorities, usually, are defined by the user - what their needs are and what makes the user journey simpler/clearer and closer to the final goal of the same user. 
The key to a good delivery is **collaboration and respect**. Always listen to the experts in your team and decide how to integrate all of that knowledge, having in mind what is best for the user.

**Comment by donbonifacio** [comment] 2018-09-14 07:05
Can you share some tips on how to take the best of a team that is partially co-located and partially remote?

**Comment by SofiaPGoncalves** [comment] 2018-09-17 13:10
Some tips:

- **Have the right equipment**. Although it seems obvious, there are things that people forget, perhaps because they never had to deal with remote teams. Having a good laptop (with camera) for when you have one-to-ones is important. A good headset for speaking/hearing is also crucial, because if the team cannot hear you properly the communication suffers. For times when a few people from each office/remote are joining for a meeting, in meeting rooms at the office make sure you have a good sound system, with a good microphone and a camera that can capture more than just one person. 

- **Make sure communication is via a tool that remote people can access** - don't rely on coffee-breaks to convey important information. If for whatever reason this happens, inform remote team what happened afterwords. 

- **Have a good way to distribute/save documents** - not just email. 

- **Have remote team in mind and make them feel part of processes**. Sometimes it will be uncomfortable and it might mean a bit more work, but making people feel integrated is crucial. If this means to set up a meeting with everyone and finding it hard to get a time when everyone is free, so be it. 

- **Stop demonizing remote work** - just because people are not in the office, they are not dead to the world. There are plenty ways to catch-up. I understand some people prefer face-to-face, but you have to accept that is not possible with everyone, so use video (instead of just voice meeting or email). 

- **Accept that sometimes things will go wrong** - and that is ok. Assess the problem, understand it, see a solution, and implement it. Sometimes communication will be broken, people will be upset, but know that is normal. Be patient and be kind to others and yourself. 

- **Understand that half your battles will be about communication and that cultural differences matter.** Don't interpret something - either an email or a comment - without full context; take a moment and try to clarify it. Whilst some cultures take a more careful approach to communication, others are more direct. There is no right or wrong, just different ways of working. Make sure you are respectful, but also respected :-)

**Comment by donbonifacio** [comment] 2018-09-18 09:26
You said that priorities are defined by the users, but how do you know the priority of something when you have thousands of users? And how do you choose innovation against evolutive maintenance?

**Comment by SofiaPGoncalves** [comment] 2018-09-26 10:50
Users are extremely important for a product manager, and by definition you are the voice of the users, as often there is no one else to "defend them" when you are deciding what to build next (you will have developers who want to build things that make more technical sense, but not for users; you will have sales people who will want to build things the clients wants - and not necessarily what the user wants; you have finance people who will want to save money).  
Before the users, for a product to be really consistent and successful, you have to have a **product strategy in place**. Otherwise, problems will arise at a later stage (it is like tech debt - you can ignore it for a while, and eventually it will become a much bigger problem, that can actually stop you from developing things you want).  
When you decide your product strategy, you define the problem you are trying to solve, the solution that you have chosen to go forward with and the steps for it. The solution chosen depends on the company, on the resources they have and what makes sense for them to do, given the entire line of products ([this is a link ](https://hackernoon.com/wtf-is-a-strategy-bcaa3fda9a31) to an excellent about strategy). 
**So, if you have users asking different things, how do you decide what to do?** You check your strategy. You see if it aligns with what you are proposing. It could well be that users want something really different, and if that is so, one should not go ahead, or be very aware of the risks. Example: an e-commerce website might have their users ask for a financial payment system. The company analyses the request and understand that is not aligned with its strategy - trying to sell products online is different from setting up a financial payment system. On the other hand, it could be that the company is trying to grow and diversify, therefore this makes sense. It all depends on your strategy! 
**How do I choose innovation against evolutive maintenance?** This is probably one of the toughest questions! I think I might not have a satisfactory answer, because it will depend, and honestly you need to use your common sense. You should not ignore things that need to be done, that are maintenance, but it can't be all you do. You should innovate, but understand that if you don't make space or take care of the underlying system, it will stop you from doing anything, sooner or later. 
As a product manager, you need to make decisions, what is best for the product, and "arm" yourself with reasons why you decided to do it: it may be data; or that in order to do X, you need Y; it could be because that is what the users want; etc.

**Comment by donbonifacio** [comment] 2018-09-27 08:10
How about hiring product managers? What kind of skills should we look for? How to distinguish junior from senior product managers?

**Comment by SofiaPGoncalves** [comment] 2018-09-30 22:02
I always thought that people look for the wrong things - often companies want someone who has done the same job for years, in the same area, and if they haven't they reject them. There is little thought put on cultural fit, which always makes me laugh, because often that is the reason why people leave.

Skills to look for:
- good problem solvers
- mediators
- analytical people
- someone who understands users' behaviour
- patient and adaptable

A good product manager is someone who is a natural **problem solver**. Not to say people who are not natural problem solvers or mediators will be bad, but the job will become too frustrating and not enjoyable. Part of a product manager's responsibility is to make sure the entire team is unblocked to work on the product - whether it be a designer, developer or content manager. The product manager needs to make sure their path is clear, and if it is not they need to understand what the problem is and how they can solve it, by unblocking it. 
Product managers need to be the person who often brings the team together - making sure everyone in the team (or a representative) sits down and talk through a problem. Often, being a **mediator** is needed to make sure people understand each other, and the best decision for the product and its users is made.
**Analytical skills** are essential as you should base your opinions on the users' needs and behaviours. They need to know how users are using the product, how they react to a change, etc., therefore understand data well.
**Understanding users' behaviour** is extremely important as a product manager needs to interpret what users want, what their goal while using the product is. The product manager is the voice of the user, therefore they need to understand users well when trying to decide what to do - balancing users' needs needs to tech debt, clients' needs, management's opinion, etc.
Finally, being a product manager is dealing with frustration. Often things do not go as expected, and the  product manager needs to bring the team together, give them motivation to go on and to find an alternative solution. Is not always easy, and sometimes one feels discouraged, but having a word of encouragement, instead of a defeated attitude is essential. This will help the product manager to **adapt** to any situation that comes by.
Some of these characteristics are not specific to product managers only, but I think product managers have a crucial role in bringing the team together and motivating people to bring their best selves forward.

Junior and product managers differ in confidence. For the time being, there is no undergraduate course one can do to become a product manager. The best product managers I have the pleasure to work with have been developers, business analytics or lawyers in the past. All of that prior experience is extremely helpful, in its own way, as it shapes who you are as a product manager. Some will be better with users, others more technical and others better with client/user management. We all learn in the job, continuously learning through others (colleagues or actual short courses about product management). Junior product managers are just not as confident in making decisions than a more senior product manager, and potentially has not experienced working with certain types of products. Nevertheless, having a fresh pair of eyes, someone looking at something like a clean canvas is amazing and I hope to encourage anyone who wants to become a product manager to come forward, because I think you have a lot to offer.

**Comment by donbonifacio** [comment] 2018-10-02 08:07
How an we grow junior product managers? How can we make them more confident? What tips can you share on mentoring/coaching product managers?

**Comment by SofiaPGoncalves** [comment] 2018-10-08 16:50
To be a mentor or a manager/leader is a big responsibility, that not every person is suited for. Being a mentor is a lot about how to understand people in their unique way, and help them move forward, within the limits of the company and job. It is fun and rewarding to be a mentor. You learn a lot about yourself and your own profession - when you have to teach something, you get to re-learn it, and in a much more profound way. 
To be a good mentor you need to give honest feedback - do not be afraid to be real. That is the only way one can truly grow. Claire Lew has amazing [posts ](https://blog.knowyourcompany.com/)about leadership - you should check her posts :-) 

The way you can grow junior managers (and let them build their trust) is by slowly giving them more freedom and responsibility regarding their product. At first, they will need a lot of support and you will need to explain how things work and how they are intertwined, but eventually, they will understand and make their own decisions without being terrified. Letting them make mistakes is also good; of course, as mentors/leaders, you should avoid letting them make huge mistakes, but small things are ok. These situations can be a learning opportunity - you make a mistake, and yet "survive". You learn that it is not that scary and also what to do in the future. The best learning opportunity lies in confidence building - the junior product manager understands that even after doing mistakes one can go on. It is a powerful message of "it is ok to mess up". Saying that one person will never make a mistake is delusional and, potentially dangerous, for when that happens they freeze and not able to go on. It is like learning how to ride a bicycle - don't let the other person take such a fall they will break a leg or arm, but if they fall and get a scratch it is ok. You will clean the wound and try again, and again, until they figure it out how to ride. Be the person who holds the bike in dangerous moments, and also the person who let’s go when the ride is smoother. 

Above all, if you are in a mentorship role be respectful and ensure you pass that message to your mentee. Be proud of whom these people want to be and help them take steps to that journey. Seeing people who you have mentored grow and be successful is one of the best feelings you will have professionally :-)

**Comment by donbonifacio** [comment] 2018-10-09 17:39
Thanks for answering my questions Sofia. As a closing note, can you suggest someone else to be interviewed?

**Comment by SofiaPGoncalves** [comment] 2018-10-09 22:51
Thank you so much for your time and for asking me to interview with you. I had lots of fun,~thinking about all your questions and how to make it clear to others. 

I nominate a few people:

- **Cindy Chang** - Senior Product Designer at Intercom (https://twitter.com/cindyjchang). I met Cindy at Jam conference last year in London and was amazed by her. Being a POC woman in tech is not easy, so I am sure she will give you a different perspective than I did. 

- **Dan Kim** - Software Engineer at Basecamp (https://twitter.com/dankim). People who work in Basecamp are super interesting and I'm in awe how they work in such a competitive market, while being bootstrapped and profitable. Their moto is "Work can wait" - Dan lives by this, and remarkably in his spare time he works, alongside with other people, in a super cool weather app (https://twitter.com/helloweatherapp)

- **Daniel Lopes** - CTO at Know Your Company (https://twitter.com/danielvlopes). Daniel is, in reality, a jack of all trades. He does it all in Know Your Company. He has an incredible back story (but he is very humble, so really ask him what he has done). He has also been involved in fighting fake news for the election of Brasil's president. 

- **Mara Zepeda** (https://twitter.com/marazepeda) and **Jennifer Brandel** (https://twitter.com/JenniferBrandel) are two fierce ladies who started an incredible movement called Zebras Unite (https://twitter.com/sexandstartups). This movement is about having ethical and diverse start-ups. I would absolutely love to see them share their experience and how they use technology to help them in their full-time jobs as CEOs on their individual companies - one in journalism - Hearken (https://twitter.com/wearehearken) and the other in social community for students - Switch Board (https://twitter.com/switchboardhq).

- **Pierre Schambacher** - Software Engineer at Zendesk (https://twitter.com/PierreSchambac). It would be interesting to hear his views how it is to work in tech in Europe vs USA. He is French and living in San Francisco now, so I am sure he has interesting views to share.

**Closed** 2018-10-21 15:46 UTC
Labels: interview
